name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/** # feature 브랜치 push 시 실행
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 환경 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Node 버전
          cache: "npm" # npm 캐시 활성화 (속도 향상)

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. Lint 실행
      - name: Run lint
        run: npm run lint

      # 5. Test 실행
      - name: Run tests
        run: npm run test || echo "No tests found, skipping"

      # 6. Build 실행
      - name: Run build
        run: npm run build
